<a href="https://colab.research.google.com/github/Ratchanontt/python_dataviz2023/blob/main/Example_for_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data From
https://data.go.th/dataset/covid-19-daily

https://www.youtube.com/watch?v=0PyXrgowm_g

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
# เข้า path ที่เราสนใจใน google drive
import os
os.chdir('/content/drive/MyDrive/Data-Viz-2023-2')

In [7]:
!ls # เช็คว่ามีไฟล์อะไรบ้างที่อยู่ใน path นั้น

 Bhumjaithai.png			 'table_merge_result (17).gsheet'
 Compare.csv				 'table_merge_result (18).gsheet'
'Copy of table_merge_result (1).gsheet'  'table_merge_result (19).gsheet'
'Copy of table_merge_result (2).gsheet'  'table_merge_result (1).gsheet'
'Copy of table_merge_result.csv'	 'table_merge_result(1).gsheet'
'Copy of table_merge_result.gsheet'	 'table_merge_result (20).gsheet'
 data_ectre_66.csv			 'table_merge_result (21).gsheet'
'DataViz22 Data'			 'table_merge_result (22).gsheet'
 ectreport2023.xlsx			 'table_merge_result (2).gsheet'
 iPrice-election.jpg			 'table_merge_result (3).gsheet'
 max_vote_region.gsheet			 'table_merge_result (4).gsheet'
 merge_chiangmai.csv			 'table_merge_result (5).gsheet'
 merge_chiangmai.gsheet			 'table_merge_result (6).gsheet'
 merge_chiangmai_new.csv		 'table_merge_result (7).gsheet'
 merge_chiangmai_neww.csv		 'table_merge_result (8).gsheet'
 merge_chiangmai_neww.gsheet		 'table_merge_result (9).gsheet'
 merge_result_project1.csv		  table_merge_result.csv
 merge_result_project1.gsheet		  table_merge_result.gsheet
 MFP_Point.csv				  table_merge_result_project1.csv
'Move Forward Party.png'		  table_merge_result_tonry.gsheet
'of table_merge_result.gsheet'		  table_merge_result_useforproject.csv
 Partylist_merge.csv			 'thai (1) (1).json'
 Pheu_Thai_RM_bk.png			 'thai (1).json'
'table_merge_result (10).gsheet'	 'thai (2).json'
'table_merge_result (11).gsheet'	  Thai-election.jpg
'table_merge_result (12).gsheet'	  thai.json
'table_merge_result (13).gsheet'	  thailand-elections-removebg-rmBK.png
'table_merge_result (14).gsheet'	  Waiitable_merge_result.gsheet
'table_merge_result (15).gsheet'	  ซ้อม
'table_merge_result (16).gsheet'

# Import Data

In [9]:
cases = pd.read_excel('/content/drive/MyDrive/DataViz23Data/confirmed-cases-since-120465.xlsx', sheet_name= 'confirmed-cases-since-120465')

In [5]:
cases.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,2022-04-12,2022-04-11,หญิง,54,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,2022-04-12,2022-04-11,หญิง,36,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,2022-04-12,2022-04-11,หญิง,31,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,2022-04-12,2022-04-11,ชาย,37,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,2022-04-12,2022-04-11,หญิง,33,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

In [34]:
cases.shape

(356612, 11)

# Checking Missing Values

In [19]:
cases.isnull().all() # เช็คค่าว่าง Null

No.                      False
announce_date            False
Notified date            False
sex                      False
age                      False
Unit                     False
nationality              False
province_of_isolation    False
risk                     False
province_of_onset        False
district_of_onset        False
dtype: bool

In [18]:
cases.isnull().any()

No.                      False
announce_date            False
Notified date            False
sex                       True
age                       True
Unit                      True
nationality               True
province_of_isolation    False
risk                     False
province_of_onset         True
district_of_onset         True
dtype: bool

In [35]:
cases_notnull = cases.dropna()

## Sex Col

In [20]:
cases[cases['sex'].isnull()] #แสดง row ที่มี sex ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
704,3906577,2022-04-12,2022-04-11,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
705,3906578,2022-04-12,2022-04-11,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
706,3906579,2022-04-12,2022-04-11,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
707,3906580,2022-04-12,2022-04-11,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
708,3906581,2022-04-12,2022-04-11,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
...,...,...,...,...,...,...,...,...,...,...,...
353978,4259851,2022-05-01,2022-04-30,NaN,35,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ดุสิต
353979,4259852,2022-05-01,2022-04-30,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,อื่นๆ,กาฬสินธุ์,เมืองกาฬสินธุ์
353980,4259853,2022-05-01,2022-04-30,NaN,25,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,บางกอกใหญ่
353981,4259854,2022-05-01,2022-04-30,NaN,25,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,บางกอกใหญ่
353982,4259855,2022-05-01,2022-04-30,NaN,36,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,หนองจอก

In [22]:
cases[cases['sex'].isnull()].dropna()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

## Age Col

In [23]:
cases[cases['age'].isnull()] #แสดง row ที่มี age ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
21,3905894,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
427,3906300,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,น่าน,อื่นๆ,น่าน,ป่ากลาง
429,3906302,2022-04-12,2022-04-11,หญิง,NaN,NaN,Thailand,น่าน,อื่นๆ,น่าน,วรนคร
549,3906422,2022-04-12,2022-04-11,หญิง,NaN,NaN,Thailand,แพร่,อื่นๆ,แพร่,เมือง
587,3906460,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,แพร่,อื่นๆ,แพร่,ร้องกวาง
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [24]:
cases[cases['age'].isnull()].dropna()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

## Unit Col

In [26]:
cases[cases['Unit'].isnull()] #แสดง row ที่มี Unit ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
21,3905894,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
427,3906300,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,น่าน,อื่นๆ,น่าน,ป่ากลาง
429,3906302,2022-04-12,2022-04-11,หญิง,NaN,NaN,Thailand,น่าน,อื่นๆ,น่าน,วรนคร
549,3906422,2022-04-12,2022-04-11,หญิง,NaN,NaN,Thailand,แพร่,อื่นๆ,แพร่,เมือง
587,3906460,2022-04-12,2022-04-11,ชาย,NaN,NaN,Thailand,แพร่,อื่นๆ,แพร่,ร้องกวาง
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [30]:
cases[cases['Unit'].isnull()].dropna()

Empty DataFrame
Columns: [No., announce_date, Notified date, sex, age, Unit, nationality, province_of_isolation, risk, province_of_onset, district_of_onset]
Index: []

## Nationality Col

In [27]:
cases[cases['nationality'].isnull()] #แสดง row ที่มี nationality ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
91,3905964,2022-04-12,2022-04-11,ชาย,69,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,หางดง
92,3905965,2022-04-12,2022-04-11,หญิง,28,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
226,3906099,2022-04-12,2022-04-11,หญิง,1,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
229,3906102,2022-04-12,2022-04-11,ชาย,13,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,หางดง
231,3906104,2022-04-12,2022-04-11,ชาย,70,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
cases[cases['nationality'].isnull()].dropna()

## province_of_onset Col

In [28]:
cases[cases['province_of_onset'].isnull()] #แสดง row ที่มี province_of_onset ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
3,3905876,2022-04-12,2022-04-11,ชาย,37,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
12,3905885,2022-04-12,2022-04-11,หญิง,28,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
14,3905887,2022-04-12,2022-04-11,ชาย,24,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
22,3905895,2022-04-12,2022-04-11,หญิง,39,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
26,3905899,2022-04-12,2022-04-11,หญิง,26,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
cases[cases['province_of_onset'].isnull()].dropna()

## District_of_onset Col

In [29]:
cases[cases['district_of_onset'].isnull()] #แสดง row ที่มี district_of_onset ว่าง

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
408,3906281,2022-04-12,2022-04-11,ชาย,30,ปี,Thailand,น่าน,อื่นๆ,น่าน,NaN
409,3906282,2022-04-12,2022-04-11,ชาย,37,ปี,Thailand,น่าน,อื่นๆ,น่าน,NaN
410,3906283,2022-04-12,2022-04-11,ชาย,59,ปี,Thailand,น่าน,อื่นๆ,น่าน,NaN
430,3906303,2022-04-12,2022-04-11,หญิง,5,ปี,Thailand,น่าน,อื่นๆ,น่าน,NaN
431,3906304,2022-04-12,2022-04-11,ชาย,71,ปี,Thailand,น่าน,อื่นๆ,น่าน,NaN
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,2022-05-01,2022-04-30,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,2022-05-01,2022-04-30,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
cases[cases['district_of_onset'].isnull()].dropna()

# Save Table

In [ ]:
import os

In [36]:
cases.columns

Index(['No.', 'announce_date', 'Notified date', 'sex', 'age', 'Unit',
       'nationality', 'province_of_isolation', 'risk', 'province_of_onset',
       'district_of_onset'],
      dtype='object')

In [37]:
cases_notnull.to_csv('case_covid.csv', index=False)

In [40]:
cases_notnull.to_csv(os.path.join('/content/drive/MyDrive/DataViz23Data','case_covid.csv'))